#server:
#  port: 8081
#  servlet:
#    context-path: /
#  ssl:
#    key-store: src/main/resources/keystore.p12
#    key-store-password: dhamecha
#    key-store-type: PKCS12
#    key-alias: tomcat

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#是否激活 swagger true or false
swagger:
  enable: true

logging:
  config: classpath:logback-spring-dev.xml

dhamecha:
  path: 192.168.105.89
task:
  resize1: C:\Users\peikangle\Desktop\images\file\